<?php
# This file was automatically generated by the MediaWiki 1.36.2
# installer. If you make manual changes, please keep track in case you
# need to recreate them later.
#
# See includes/DefaultSettings.php for all configurable settings
# and their default values, but don't forget to make changes in _this_
# file, not there.
#
# Further documentation for configuration settings may be found at:
# https://www.mediawiki.org/wiki/Manual:Configuration_settings



# Protect against web entry
if ( !defined( 'MEDIAWIKI' ) ) {
	exit;
}


## Uncomment this to disable output compression
# $wgDisableOutputCompression = true;

$wgSitename = "Gyaanipedia";
$wgMetaNamespace = "Gyaanipedia";

## The URL base path to the directory containing the wiki;
## defaults for all runtime URL paths are based off of this.
## For more information on customizing the URLs
## (like /w/index.php/Page_title to /wiki/Page_title) please see:
## https://www.mediawiki.org/wiki/Manual:Short_URL
$wgScriptPath = '';

$wgResourceBasePath = $wgScriptPath;


## The protocol and server name to use in fully-qualified URLs
$wgServer = "http://mirror.gyaanipedia.com";

## The URL path to static resources (images, scripts, etc.)


## The URL paths to the logo.  Make sure you change this from the default,
## or else you'll overwrite your logo when you upgrade!
$wgFavicon = "https://static.miraheze.org/gyaanipediawiki/e/eb/Gyaanipedia_logo1.png";

$wgLogos = [ '1x' => "https://static.miraheze.org/commonsgyaanipediawiki/5/50/Gyaanipedia_desktop_logo.png", 
'wordmark' => [
		'src' => "https://static.miraheze.org/commonsgyaanipediawiki/3/3c/Gyaanipedia_text_logo_bold.png",
		
		'width' => 200,
		'height' => 30,
],

];



## UPO means: this is also a user preference option

$wgEnableEmail = true;
$wgEnableUserEmail = true; # UPO

$wgEmergencyContact = "mail@shaunak.in";
$wgPasswordSender = "mail@shaunak.in";

$wgEnotifUserTalk = false; # UPO
$wgEnotifWatchlist = false; # UPO
$wgEmailAuthentication = true;

## Database settings
$wgDBtype = "mysql";
$wgDBserver = "sql102.byetcluster.com";
$wgDBname = "b32_30076777_434";
$wgDBuser = "30076777_1";
$wgDBpassword = "!1Epz.nS87";

# MySQL specific settings
$wgDBprefix = "mwo5_";

# MySQL table options to use during installation or update
$wgDBTableOptions = "ENGINE=InnoDB, DEFAULT CHARSET=binary";

# Shared database table
# This has no effect unless $wgSharedDB is also set.
$wgSharedTables[] = "actor";

## Shared memory settings
$wgMainCacheType = CACHE_NONE;
$wgMemCachedServers = [];

## To enable image uploads, make sure the 'images' directory
## is writable, then set this to true:
$wgEnableUploads = true;
$wgMFNearby = true;
#$wgUseImageMagick = true;
#$wgImageMagickConvertCommand = "/usr/bin/convert";

# InstantCommons allows wiki to use images from https://commons.wikimedia.org
$wgUseInstantCommons = false;

# Periodically send a pingback to https://www.mediawiki.org/ with basic data
# about this MediaWiki instance. The Wikimedia Foundation shares this data
# with MediaWiki developers to help guide future development efforts.
$wgPingback = true;

## If you use ImageMagick (or any other shell command) on a
## Linux server, this will need to be set to the name of an
## available UTF-8 locale. This should ideally be set to an English
## language locale so that the behaviour of C library functions will
## be consistent with typical installations. Use $wgLanguageCode to
## localise the wiki.
$wgShellLocale = "en_US.utf8";

## Set $wgCacheDirectory to a writable directory on the web server
## to make your wiki go slightly faster. The directory should not
## be publicly accessible from the web.
#$wgCacheDirectory = "$IP/cache";

# Site language code, should be one of the list in ./languages/data/Names.php
$wgLanguageCode = "en";

$wgSecretKey = "3540b7f838f52ecab35eb5440d0a68ec06f86bf9394203128bbf960cc8d99b6b";

# Changing this will log out all existing sessions.
$wgAuthenticationTokenVersion = "1";

# Site upgrade key. Must be set to a string (default provided) to turn on the
# web installer while LocalSettings.php is in place
$wgUpgradeKey = "mk4152vmlnt70jpl";

## For attaching licensing metadata to pages, and displaying an
## appropriate copyright notice / icon. GNU Free Documentation
## License and Creative Commons licenses are supported so far.
$wgRightsPage = ""; # Set to the title of a wiki page that describes your license/copyright
$wgRightsUrl = "https://www.gyaanipedia.com";
$wgRightsText = "Gyaanipedia";
$wgRightsIcon = "https://mirror.gyaanipedia.com/images/a/a4/Footer_small.png";

# Path to the GNU diff3 utility. Used for conflict resolution.
$wgDiff3 = "/usr/bin/diff3";

## Default skin: you can change the default skin. Use the internal symbolic
## names, ie 'vector', 'monobook':
$wgDefaultSkin = "Vector";
$wgMFDefaultSkinClass = 'SkinMinerva';

# Enabled skins.
# The following skins were automatically enabled:
wfLoadSkin( 'MonoBook' );
wfLoadSkin( 'Timeless' );
wfLoadSkin( 'Vector' );
wfLoadSkin( 'MinervaNeue' );



wfLoadExtension( 'VisualEditor' );
wfLoadExtension( 'GeoData' );
wfLoadExtension( 'MobileFrontend' );
wfLoadExtension( 'CSS' );
wfLoadExtension( 'Cite' );
wfLoadExtension( 'CiteThisPage' );

wfLoadExtension( 'ConfirmEdit' );
wfLoadExtension( 'Gadgets' );
wfLoadExtension( 'ImageMap' );
wfLoadExtension( 'InputBox' );
wfLoadExtension( 'Interwiki' );

wfLoadExtension( 'LocalisationUpdate' );
wfLoadExtension( 'MultimediaViewer' );
wfLoadExtension( 'Nuke' );
wfLoadExtension( 'OATHAuth' );
wfLoadExtension( 'PageImages' );
wfLoadExtension( 'ParserFunctions' );
wfLoadExtension( 'PdfHandler' );
wfLoadExtension( 'Poem' );

wfLoadExtension( 'Renameuser' );
wfLoadExtension( 'ReplaceText' );
wfLoadExtension( 'Scribunto' );
wfLoadExtension( 'SecureLinkFixer' );
wfLoadExtension( 'SpamBlacklist' );

wfLoadExtension( 'TemplateData' );
wfLoadExtension( 'TitleBlacklist' );
wfLoadExtension( 'WikiEditor' );
wfLoadExtension( 'AdminLinks' );
wfLoadExtension( 'TemplateSandbox' );
wfLoadExtension( 'AddHTMLMetaAndTitle' );
wfLoadExtension( 'Babel' );
wfLoadExtension( 'Loops' );
wfLoadExtension( 'TemplateStyles' );
wfLoadExtension( 'Variables' );
wfLoadExtension( 'Theme' );








# End of automatically generated settings.
# Add more configuration options below.

$wgTmpDirectory = "/home/vol3_3/byethost32.com/b32_30076777/tmp_toj11k";

